# Generated by Django 4.1.4 on 2022-12-09 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('can_view_other_persons', 'Pozwala przeglądać obiekty modelu Osoba, zalogowanym użytkownikom, którzy nie są własicielami danego obiektu modelu Osoba')]},
        ),
        migrations.AddField(
            model_name='osoba',
            name='wlasciciel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='osoby', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
