# Generated by Django 4.1.2 on 2022-10-20 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_druzyna_osoba_druzyna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='druzyna',
        ),
        migrations.AddField(
            model_name='osoba',
            name='druzynaa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.druzyna'),
        ),
    ]
