# Generated by Django 4.1.2 on 2022-10-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_osoba_druzyna_osoba_druzynaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osoba',
            old_name='druzynaa',
            new_name='druzyna',
        ),
    ]
