# Generated by Django 4.1.2 on 2022-10-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_rename_druzynaa_osoba_druzyna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='iduser',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
