# Generated by Django 4.1.2 on 2022-10-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_user_iduser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='iduser',
            field=models.IntegerField(db_column='idUser', default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
