# Generated by Django 4.1.2 on 2022-11-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('can_view_other_persons', 'Pozwala przeglądać obiekty modelu Osoba, zalogowanym użytkownikom, którzy nie są własicielami danego obiektu modelu Osoba')]},
        ),
    ]
